# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/anasfanani"

[social.params]
icon = "brand-github"
newtab = true

[[social]]
identifier = "stackoverflow"
name = "Stack Overflow"
url = "https://stackoverflow.com/users/12716228"

[social.params]
icon = "brand-stackoverflow"
newtab = true

[[social]]
identifier = "xda"
name = "XDA Forums"
url = "https://xdaforums.com/m/9512959"

[social.params]
icon = "brand-xda"
newtab = true