### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
main: []
social:
  - identifier: github
    name: GitHub
    url: 'https://github.com/anasfanani'
    params:
      icon: brand-github
      newTab: true
  - identifier: twitter
    name: X / Twitter
    url: 'https://twitter.com/anasfanani3'
    params:
      icon: brand-x
      newTab: true

